version: '3.8'

services:
  # Injin Fata AI Ultra Backend
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AQ.Ab8RN6JuD1a5NyJ4-SdvZi29gBXD9JbpinfTR58NbN-zmMfoTg
      - DATABASE_URL=postgresql+asyncpg://postgres:fata_secret_2026@postgres_db:5432/fata_auth
      - MONGO_URL=mongodb://mongo_db:27017
      - REDIS_URL=redis://redis_cache:6379/0
    depends_on:
      - postgres_db
      - mongo_db
      - redis_cache

  # Rumbun Bayani na Postgres (Auth & Users)
  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fata_secret_2026
      POSTGRES_DB: fata_auth
    ports:
      - "5432:5432"

  # Rumbun Bayani na Mongo (Chat History)
  mongo_db:
    image: mongo:6.0
    ports:
      - "27017:27017"

  # Injin Caching na Redis (Speed & Rate Limiting)
  redis_cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"